import 'package:flutter/services.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher_string.dart';

import '../../core/constants/app_strings.dart';
import '../../core/utils/currency_formatter.dart';
import '../../core/utils/date_utils.dart';
import '../../data/models/payment_model.dart';

class PaymentShareService {
  const PaymentShareService._();

  static String buildReceiptText(
    PaymentModel payment, {
    String? recordedBy,
    bool qrAttached = false,
  }) {
    final tenantName = payment.tenant?.fullName ?? '-';
    final roomNumber = payment.room?.roomNumber ?? '-';
    final latestEntry = payment.entries.isNotEmpty
        ? payment.entries.last
        : null;
    final latestPaid = latestEntry?.amountPaid ?? payment.amountPaid;
    final latestMethod = latestEntry?.paymentMethod ?? payment.paymentMethod;
    final latestDate = latestEntry?.paymentDate ?? payment.paymentDate;
    final status = payment.remainingAmount <= 0
        ? 'PAID'
        : payment.amountPaid > 0
        ? 'PARTIAL'
        : 'PENDING';

    final buffer = StringBuffer()
      ..writeln('*RentFlow Rent Receipt*')
      ..writeln('_Rent, Tracked. Family, Synced._')
      ..writeln()
      ..writeln('*Receipt:* ${payment.receiptNumber}')
      ..writeln('*Status:* $status')
      ..writeln('*Room:* $roomNumber')
      ..writeln('*Tenant:* $tenantName')
      ..writeln('*Month:* ${payment.month}')
      ..writeln()
      ..writeln('*Payment Breakdown*')
      ..writeln(
        'Monthly rent: ${CurrencyFormatter.inr(payment.monthlyRentDue)}',
      );

    if (payment.carriedForwardAmount > 0) {
      buffer.writeln(
        'Previous pending: ${CurrencyFormatter.inr(payment.carriedForwardAmount)}',
      );
    }

    if (payment.manualDueAmount > 0) {
      buffer.writeln(
        'Extra/manual due: ${CurrencyFormatter.inr(payment.manualDueAmount)}',
      );
      final manualReason = payment.manualDueRemark?.trim();
      if (manualReason != null && manualReason.isNotEmpty) {
        buffer.writeln('Manual due reason: $manualReason');
      }
    }

    buffer
      ..writeln('Total payable: *${CurrencyFormatter.inr(payment.totalDue)}*')
      ..writeln('Paid so far: *${CurrencyFormatter.inr(payment.amountPaid)}*')
      ..writeln(
        'Remaining: *${CurrencyFormatter.inr(payment.remainingAmount)}*',
      );

    if (payment.advanceAmount > 0) {
      buffer.writeln(
        'Advance/extra paid: ${CurrencyFormatter.inr(payment.advanceAmount)}',
      );
    }

    buffer
      ..writeln()
      ..writeln('*Latest Collection*')
      ..writeln('Paid now: ${CurrencyFormatter.inr(latestPaid)}')
      ..writeln('Method: ${_methodLabel(latestMethod)}')
      ..writeln('Date: ${AppDateUtils.formatDate(latestDate)}')
      ..writeln(
        'Recorded by: ${recordedBy ?? payment.recordedBy?.name ?? '-'}',
      );

    final remark = payment.remark?.trim();
    if (remark != null && remark.isNotEmpty) {
      buffer.writeln('Remark: $remark');
    }

    final installments = payment.entries
        .where((entry) => entry.amountPaid > 0)
        .toList(growable: false);
    if (installments.length > 1) {
      buffer
        ..writeln()
        ..writeln('*Installments*');
      for (var index = 0; index < installments.length; index += 1) {
        final entry = installments[index];
        buffer.writeln(
          '${index + 1}. ${CurrencyFormatter.inr(entry.amountPaid)} | '
          '${_methodLabel(entry.paymentMethod)} | '
          '${AppDateUtils.formatDate(entry.paymentDate)}',
        );
      }
    }

    buffer
      ..writeln()
      ..writeln('*Payment QR*')
      ..writeln(
        qrAttached
            ? 'QR image is attached with this receipt. Scan it to pay remaining rent.'
            : 'Use "Share receipt + QR" in RentFlow to send the QR image along with this receipt.',
      )
      ..writeln()
      ..writeln('_Generated by RentFlow - Family Rent Manager_');

    return buffer.toString();
  }

  static Future<void> shareWhatsAppText(
    PaymentModel payment, {
    String? recordedBy,
  }) async {
    final text = buildReceiptText(payment, recordedBy: recordedBy);
    final encodedText = Uri.encodeComponent(text);
    final phone = _whatsAppPhone(payment);
    final url = phone == null
        ? 'whatsapp://send?text=$encodedText'
        : 'https://wa.me/$phone?text=$encodedText';

    final launched = await launchUrlString(url);
    if (!launched && phone != null) {
      await launchUrlString('whatsapp://send?text=$encodedText');
    }
  }

  static Future<void> shareReceiptWithQr(
    PaymentModel payment, {
    String? recordedBy,
  }) async {
    final qrBytes = await _loadPaymentQrBytes();
    await SharePlus.instance.share(
      ShareParams(
        text: buildReceiptText(
          payment,
          recordedBy: recordedBy,
          qrAttached: true,
        ),
        files: [
          XFile.fromData(
            qrBytes,
            mimeType: 'image/png',
            name: 'rentflow-payment-qr.png',
          ),
        ],
      ),
    );
  }

  static Future<void> shareReceiptPdfWithQr({
    required PaymentModel payment,
    required Future<Uint8List> Function() loadPdf,
    String? recordedBy,
  }) async {
    final pdfBytes = await loadPdf();
    final qrBytes = await _loadPaymentQrBytes();
    final safeReceipt = payment.receiptNumber
        .replaceAll(RegExp(r'[^a-zA-Z0-9_-]'), '-')
        .toLowerCase();

    await SharePlus.instance.share(
      ShareParams(
        text: buildReceiptText(
          payment,
          recordedBy: recordedBy,
          qrAttached: true,
        ),
        files: [
          XFile.fromData(
            pdfBytes,
            mimeType: 'application/pdf',
            name: '$safeReceipt.pdf',
          ),
          XFile.fromData(
            qrBytes,
            mimeType: 'image/png',
            name: 'rentflow-payment-qr.png',
          ),
        ],
      ),
    );
  }

  static Future<Uint8List> _loadPaymentQrBytes() async {
    final data = await rootBundle.load(AppStrings.paymentQrAsset);
    return data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  }

  static String? _whatsAppPhone(PaymentModel payment) {
    final raw = payment.tenant?.whatsappNumber?.trim().isNotEmpty == true
        ? payment.tenant!.whatsappNumber!
        : payment.tenant?.phone;
    if (raw == null || raw.trim().isEmpty) {
      return null;
    }

    final digits = raw.replaceAll(RegExp(r'[^0-9]'), '');
    if (digits.length == 10) {
      return '91$digits';
    }
    return digits.isEmpty ? null : digits;
  }

  static String _methodLabel(String method) {
    return method
        .split('_')
        .where((part) => part.isNotEmpty)
        .map((part) => '${part[0].toUpperCase()}${part.substring(1)}')
        .join(' ');
  }
}
